"use client";

import { useRouter } from "next/navigation";
import Link from "next/link";
import { Sparkles, Zap, Lock, LogIn, Brain, Box, Hammer, Code, ShieldCheck } from "lucide-react";
import { useAuth } from "@/client/hooks/use-auth";
import { Button } from "@/client/components/ui/button";
import { Typography } from "@/client/components/ui/typography";
import { Container } from "@/client/components/ui/container";
import { Section } from "@/client/components/ui/section";
import { Badge } from "@/client/components/ui/badge";

export default function Home() {
  const { user } = useAuth();
  const router = useRouter();

  const handleStartDesigning = () => {
    if (user) {
      router.push("/dashboard");
    } else {
      router.push("/login?redirect_to=/dashboard");
    }
  };

  return (
    <div className="flex-1 flex flex-col">
      {/* Hero + CTA Section */}
      <Section spacing="large" className="relative overflow-visible">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-blue-200/30 via-white to-white" />

        <Container size="small" className="text-center space-y-10">
          {/* Hero Copy */}
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-8 duration-700">
            <Badge variant="brand" className="px-4 py-2 gap-2 h-auto text-sm">
              <Sparkles className="h-4 w-4" />
              Agentic 3D Modeler
            </Badge>
            
            <Typography variant="h1" className="leading-[1.1]">
              Build 3D models with AI.{" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-blue-700">
                Just describe it.
              </span>
            </Typography>
            
            <Typography variant="lead" className="max-w-xl mx-auto">
              Lattice builds real watertight 3D models (STLs) through natural conversation with a powerful coding agent. No CAD experience required.
            </Typography>
          </div>

          {/* Start Session Button */}
          <div className="relative z-10 animate-in fade-in slide-in-from-bottom-12 duration-1000 delay-200">
            <Button size="lg" variant="brand" className="h-14 px-8 text-lg rounded-2xl" onClick={handleStartDesigning}>
              <Sparkles className="w-5 h-5 mr-2" />
              Start Designing Now
            </Button>
          </div>
        </Container>
      </Section>

      {/* Features Section */}
      <Section background="muted" border="top">
        <Container size="default" className="grid lg:grid-cols-2 gap-16 items-center">
          {/* Feature List */}
          <div className="space-y-8 animate-in fade-in slide-in-from-left-8 duration-1000 delay-300">
            <Typography variant="h2">
              Agentic 3D Modeling Redefined
            </Typography>
            <div className="grid gap-8">
              {[
                {
                  icon: Brain,
                  title: "Natural Language to STL",
                  desc: "Describe your ideas in plain English. Our coding agent automatically writes industry-grade build123d Python script to construct the exact geometry.",
                },
                {
                  icon: Hammer,
                  title: "Iterative Prototyping",
                  desc: "Refine your designs in natural conversation. Ask the agent to add fillets, apply chamfers, modify tolerances, or cut mounting holes on the fly.",
                },
                {
                  icon: ShieldCheck,
                  title: "Isolated Kubernetes Sandboxes",
                  desc: "Every design workspace executes inside a secure, ephemeral container equipped with OpenCascade, Python CAD libraries, and mesh validation tools.",
                },
                {
                  icon: Code,
                  title: "Inspect & Edit Code",
                  desc: "Lattice shows you the exact Python CAD code generated by the agent. You have total control over the math and constructive solid geometry.",
                },
              ].map((item, i) => (
                <div key={i} className="flex gap-5">
                  <div className="shrink-0 w-12 h-12 rounded-2xl bg-blue-50 flex items-center justify-center text-blue-600">
                    <item.icon className="w-6 h-6" />
                  </div>
                  <div>
                    <Typography variant="large" className="mb-1">{item.title}</Typography>
                    <Typography variant="muted" className="leading-relaxed">{item.desc}</Typography>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Mockup Chat Card */}
          <div className="relative group animate-in fade-in slide-in-from-right-8 duration-1000 delay-400">
            <div className="absolute inset-0 bg-blue-200 rounded-3xl blur-3xl opacity-20 -rotate-3 transition-transform group-hover:rotate-3 duration-1000" />

            <div className="relative bg-white border border-gray-200 shadow-xl rounded-3xl p-6 space-y-5">
              {/* File header */}
              <div className="flex items-center justify-between border-b border-gray-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center">
                    <Box className="h-6 w-6 text-blue-600" />
                  </div>
                  <div className="text-left">
                    <Typography variant="small" className="font-bold">Bracket_Design.stl</Typography>
                    <Typography variant="tiny">Watertight Mesh</Typography>
                  </div>
                </div>
                <Badge variant="success">Ready</Badge>
              </div>

              {/* Chat bubbles (decorative) */}
              <div className="space-y-3 opacity-60 select-none">
                <div className="flex justify-end">
                  <div className="bg-gray-100 rounded-2xl rounded-tr-sm px-4 py-2.5 text-[11px] font-medium text-gray-700 max-w-[85%]">
                    I need a custom mounting bracket for a 2020 extrusion with a 5mm hole.
                  </div>
                </div>
                <div className="flex justify-start">
                  <div className="bg-blue-600 rounded-2xl rounded-tl-sm px-4 py-2.5 text-[11px] font-medium text-white max-w-[85%]">
                    Done! I've executed a build123d script in the sandbox to build the bracket and generated the 3D STL model.
                  </div>
                </div>
                <div className="flex justify-end">
                  <div className="bg-gray-100 rounded-2xl rounded-tr-sm px-4 py-2.5 text-[11px] font-medium text-gray-700 max-w-[85%]">
                    Can you chamfer the top edges by 2mm?
                  </div>
                </div>
              </div>

              {/* Login Gate Overlay */}
              {!user && (
                <div className="absolute inset-4 top-16 flex items-center justify-center z-20">
                  <div className="bg-white/95 backdrop-blur-md border border-blue-100 p-8 rounded-2xl shadow-xl text-center space-y-4 max-w-[280px]">
                    <div className="w-12 h-12 bg-blue-50 rounded-full flex items-center justify-center mx-auto">
                      <Lock className="w-6 h-6 text-blue-600" />
                    </div>
                    <Typography variant="h4">Login to start modeling</Typography>
                    <Typography variant="small" className="text-gray-500 leading-relaxed">
                      Receive free CAD sandbox credits and start creating 3D models in seconds.
                    </Typography>
                    <Button asChild variant="brand" className="w-full h-12 rounded-xl">
                      <Link href="/login">
                        <LogIn className="w-4 h-4 mr-2" />
                        Sign In Now
                      </Link>
                    </Button>
                  </div>
                </div>
              )}
            </div>
          </div>
        </Container>
      </Section>

      {/* Minimal Footer */}
      <footer className="border-t border-gray-100 py-8 px-4 bg-white">
        <div className="container mx-auto flex flex-col sm:flex-row justify-between items-center gap-4 text-sm text-gray-400">
          <div className="flex items-center gap-6">
            <Link href="/terms" className="hover:text-gray-900 transition-colors">Terms</Link>
            <Link href="/privacy" className="hover:text-gray-900 transition-colors">Privacy</Link>
          </div>
          <p>&copy; {new Date().getFullYear()} Lattice. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
