import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-gray-900">
      <main className="container mx-auto px-4 py-12 md:py-20 max-w-4xl">
        <h1 className="text-4xl md:text-5xl font-heading font-bold mb-8">Terms and Conditions</h1>
        <p className="text-gray-500 mb-12">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="prose prose-lg prose-gray max-w-none space-y-12">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Introduction</h2>
            <p className="text-gray-600 leading-relaxed">
              Welcome to Lattice ("we," "our," or "us"). By accessing or using our website and AI-powered agentic 3D modeling
              services (collectively, the "Service"), you agree to be bound by these Terms and Conditions ("Terms"). If
              you do not agree to these Terms, please do not use our Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Description of Service</h2>
            <p className="text-gray-600 leading-relaxed">
              Lattice provides an AI-powered tool that assists users in designing, constructing, and managing 3D models.
              The Service utilizes sandboxed coding agents to generate, execute, and validate Python CAD code (build123d)
              and output high-quality STL models.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. AI Disclaimer</h2>
            <p className="text-gray-600 leading-relaxed">
              Our Service uses artificial intelligence to analyze documents and generate responses. While we strive for
              accuracy, AI systems can occasionally produce incorrect, misleading, or biased information
              ("hallucinations").
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-gray-600">
              <li>
                You should always verify the accuracy of any information, summaries, or form-filling suggestions
                provided by the Service.
              </li>
              <li>Lattice is not a substitute for professional legal, financial, or medical advice.</li>
              <li>We are not responsible for any errors or omissions in the content generated by the AI.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">4. User Responsibilities</h2>
            <p className="text-gray-600 leading-relaxed">
              You are responsible for your use of the Service and for any content you upload or generate. You agree not
              to:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-gray-600">
              <li>Upload any documents containing illegal, harmful, threatening, or sexually explicit content.</li>
              <li>
                Use the Service for any unlawful purpose or in violation of any local, state, national, or international
                law.
              </li>
              <li>Attempt to reverse engineer, decompile, or hack the Service.</li>
              <li>Share your account credentials with third parties.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Intellectual Property</h2>
            <p className="text-gray-600 leading-relaxed">
              You retain all rights to the documents you upload to the Service. By uploading documents, you grant us a
              license to process, analyze, and store them solely for the purpose of providing the Service to you.
            </p>
            <p className="text-gray-600 leading-relaxed mt-4">
              The Lattice interface, branding, and underlying technology are the property of Lattice and are protected
              by copyright and other intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed">
              To the maximum extent permitted by law, Lattice shall not be liable for any indirect, incidental, special,
              consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or
              indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2 text-gray-600">
              <li>Your use or inability to use the Service.</li>
              <li>Any inaccuracies or errors in the AI-generated content.</li>
              <li>Unauthorized access to or use of our servers and/or any personal information stored therein.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Changes to Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the
              new Terms on this page and updating the "Last updated" date. Your continued use of the Service after any
              such changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Contact Us</h2>
            <p className="text-gray-600 leading-relaxed">
              If you have any questions about these Terms, please contact us at support@lattice.com.
            </p>
          </section>
        </div>
      </main>

      <footer className="bg-gray-50 border-t border-gray-100 mt-20">
        <div className="container mx-auto px-4 py-12 flex flex-col md:flex-row justify-between items-center gap-6">
          <p className="text-sm text-gray-400">&copy; {new Date().getFullYear()} Lattice. All rights reserved.</p>
          <div className="flex items-center gap-8">
            <Link href="/privacy" className="text-sm text-gray-500 hover:text-gray-900 transition-colors">
              Privacy Policy
            </Link>
            <Link href="/" className="text-sm text-gray-500 hover:text-gray-900 transition-colors">
              Home
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
